### ISSUE TITLE
Github PR plugin does not seem to work for private repo

### ISSUE THREAD

**Issue by ArchanaSwamy** [RoadieHQ/backstage-plugin-github-pull-requests#32]
Added the RoadieHQ/backstage-plugin-github-pull-requests version 0.6.2 via npm manager. 

## Expected Behavior
After the Github SSO login, I expect the PR details to be displayed  from my private repo. The GITHUB_TOKEN that is set here to be accepted by  the plugin

```
integrations:
  github:
    - host: github.com
      apiBaseUrl: https://api.github.com
      token:
        $env: GITHUB_TOKEN
```

## Current Behavior
It allowed to SSO into Github but  the plugin doesn't accept the github token. The result of this is I get a 404 Not found and it seems it is passing some sort of an authentication key which is not mine or not set in the GITHUB_TOKEN
https://github.com/RoadieHQ/backstage-plugin-github-pull-requests/blob/301c329f15090aee57e1a89ce0ede081f6607a0b/src/api/GithubPullRequestsClient.ts#L43

## Steps to Reproduce

1. Add the RoadieHQ/backstage-plugin-github-pull-requests version 0.6.2 in app package.jso and plugin.ts
2. Set the github_token in the app-config.yaml which is

```
integrations:
  github:
    - host: github.com
      apiBaseUrl: https://api.github.com
      token:
        $env: GITHUB_TOKEN
catalog:
  rules:
    - allow: [Component, API, Group, User, Template, Location]
  locations:
    - type: file
      target: /app/catalog-info.yaml
  processors:
    githubOrg:
      providers:
        - target: https://github.com
          token:
            $env: GITHUB_TOKEN
scaffolder:
  github:
    token:
      $env: GITHUB_TOKEN
    visibility: private # or 'internal' or 'private'

auth:
  providers:
    github:
      development:
        clientId:
          $env: AUTH_GITHUB_CLIENT_ID
        clientSecret:
          $env: AUTH_GITHUB_CLIENT_SECRET`
```

## Context

This doesn't let me use any of the Github PR related features.

## Your Environment

- Plugin Version : 0.6.2
- Backstage version : 0.3.0
- NodeJS Version (e.g. v12): v 12
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS
- Browser Information (e.g. chrome 85): Chrome v86
